//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administration_Gagarkina.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Overtime
    {
        public int OvertimeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date_Recycling { get; set; }
        public Nullable<int> Number_Of_Hours { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
